Project/admin/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired


class CreateRoleForm(FlaskForm):
    name = StringField('Role Name', validators=[DataRequired()])
    submit = SubmitField('Create')


class SearchForm(FlaskForm):
    search_query = StringField('Role Name')
    submit = SubmitField('Search')

Project/admin/views.py
from flask import Blueprint, flash, render_template, request, url_for
from flask_principal import Permission, RoleNeed
from sqlalchemy.exc import SQLAlchemyError

from admin.forms import CreateRoleForm
from auth.models import Role, User, UserRoles
from base_model import db
from helpers import handle_duplicate_column
from werkzeug.utils import redirect

admin = Blueprint('admin', __name__, template_folder='templates', url_prefix='/admin')

# Create a permission with a single Need, in this case a RoleNeed.
admin_permission = Permission(RoleNeed('Admin'))


@admin.route("/roles/create", methods=["GET", "POST"])
@admin_permission.require(403)
def create_role():
    form = CreateRoleForm()
    if form.validate_on_submit():
        role = Role()
        form.populate_obj(obj=role)
        db.session.add(role)
        try:
            db.session.commit()
            flash("Successfully created role {}".format(role.name), "success")
        except SQLAlchemyError as e:
            print(e)
            handle_duplicate_column(str(e.orig))
            db.session.rollback()
    return render_template("create_role.html", form=form)


@admin.route("/roles/list", methods=["GET"])
@admin_permission.require(403)
def list_roles():
    roles = Role.query.all()
    return render_template("list_roles.html", roles=roles)


@admin.route("/role/delete", methods=["POST"])
@admin_permission.require(403)
def delete_role():
    role_id = request.form.get("role_id", 0, type=int)

    if role_id > 0:
        role = Role.query.get(role_id)
        if role.name == "Admin":
            flash("Prevented the deletion of Admin", "danger")
        else:
            for assoc in role.users:
                db.session.delete(assoc)
            db.session.delete(role)
            try:
                db.session.commit()
                flash("Deleted role {}".format(role.name), "success")
            except SQLAlchemyError as e:
                db.session.rollback()
                print(e)
                flash("Error deleting role, check the logs", "danger")
    else:
        flash("Invalid role", "danger")
    return redirect(url_for("admin.list_roles"))


@admin.route("/roles/assign", methods=["GET", "POST"])
@admin_permission.require(403)
def assign_roles():
    if request.method == 'POST':
        role_ids = request.form.getlist("role_id[]")
        user_ids = request.form.getlist("user_id[]")
        print(role_ids)
        print(user_ids)
        users = User.query.filter(User.id.in_(user_ids)).all()
        print(users)
        roles = Role.query.filter(Role.id.in_(role_ids)).all()
        for user in users:
            for role in roles:
                ur = UserRoles()
                ur.role = role
                user.roles.append(ur)
                db.session.add(user)
                try:
                    db.session.commit()
                    flash(f"Added role {role.name} to {user.username}", "success")
                except SQLAlchemyError as e:
                    db.session.rollback()
                    print(e)
                    flash(f"User {user.username} already has role {role.name}", "danger")
    roles = Role.query.all()
    search = request.form.get("username", "")
    if not search:
        # TODO look for query parameter of username
        pass
    if search:
        like_search = "%{}%".format(search)
        users = User.query.filter(User.username.like(like_search)).limit(10).all()
    else:
        users = User.query.limit(10).all()
    return render_template("assign_roles.html", roles=roles, users=users, username=search)


@admin.route("/role/unassign", methods=["POST"])
@admin_permission.require(403)
def unassign_role():
    user_id = request.form.get("user_id", 0, type=int)
    role_id = request.form.get("role_id", 0, type=int)
    search = request.form.get("username", "")
    if user_id <= 0 or role_id <= 0:
        flash("Invalid user or role selected", "danger")
    else:
        user = User.query.get(user_id)
        if not user:
            flash("Error looking up user", "danger")
        else:
            for assoc in user.roles:
                if assoc.role.id == role_id:
                    db.session.delete(assoc)
                    try:
                        db.session.commit()
                        flash(f"Removed role {assoc.role.name} from {user.username}", "success")
                    except SQLAlchemyError as e:
                        print(e)
                        db.session.rollback()
                        flash(f"An error occurred removing the role {assoc.role.name} from {user.username}", "danger")
                    break
    return redirect(url_for("admin.assign_roles", username=search))

Project/main.py
# from https://towardsdatascience.com/deploy-to-google-cloud-run-using-github-actions-590ecf957af0
import os
import sys

from flask import Flask
from flask_login import LoginManager, current_user
from flask_principal import Principal, identity_loaded, UserNeed, RoleNeed

from sqlalchemy import MetaData



# added so modules can be found between the two different lookup states:
# from tests and from regular running of the app
CURR_DIR = os.path.dirname(os.path.abspath(__file__))
print(CURR_DIR)
sys.path.append(CURR_DIR)

login_manager = LoginManager()


# app = Flask(__name__)
def create_app(config_filename=''):
    app = Flask(__name__)
    # add db connection
    # default to sqlite if DB_URL isn't setup properly
    db_url = os.environ.get("DB_URL", "sqlite:///mydb.db")
    if db_url:
        app.config["SQLALCHEMY_DATABASE_URI"] = db_url
        app.config["SQLALCHEMY_TRACK_MODIFICATIONS"] = False

    # configure flask-login
    # use an environment variable to pull the secret key
    # having this random each app start will clear the session every time the app reloads
    # set SECRET_KEY the same way you do DB_URL, just a different value
    SECRET_KEY = os.environ.get("SECRET_KEY", "thisisforlocal") # os.urandom(32 )
    app.config["SECRET_KEY"] = SECRET_KEY

    # app.config.from_pyfile(config_filename)
    register_blueprints(app)
    register_extensions(app)

    setup_db(app)
    return app


def register_extensions(app):
    print("registering extensions")
    from auth.models import db
    db.init_app(app)
    Principal(app) # https://pythonhosted.org/Flask-Principal/
    login_manager.init_app(app)


def setup_db(app):
    with app.app_context():
        print("create all")
        from auth.models import db
        db.create_all()
        db.session.commit()



def register_blueprints(app):
    from auth.models import User

    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(user_id)

    @identity_loaded.connect_via(app)
    def on_identity_loaded(sender, identity):
        # Set the identity user object
        identity.user = current_user
        # Add the UserNeed to the identity
        if hasattr(current_user, 'id'):
            identity.provides.add(UserNeed(current_user.id))

        # Assuming the User model has a list of roles, update the
        # identity with the roles that the user provides
        if hasattr(current_user, 'roles'):
            print("User has roles {}".format(current_user.roles))
            for assoc in current_user.roles:
                if assoc.role is None:
                    continue
                print(assoc.role.name)
                identity.provides.add(RoleNeed(assoc.role.name))
        else:
            print("User doesn't have any roles")

    from views.hello import hello
    app.register_blueprint(hello)
    from auth.views import auth
    app.register_blueprint(auth)
    from admin.views import admin
    app.register_blueprint(admin)


if __name__ == "__main__":
    app = create_app()

    app.run(debug=True, host='0.0.0.0', port=int(os.environ.get('PORT', 8081)))
    from auth.models import db
    metadata = MetaData()
    metadata.reflect(bind=db.engine)
    # debugging output to verify tables were created
    for table in metadata.sorted_tables:
        print(table)

Project/views/hello.py
from flask import Blueprint, request
hello = Blueprint('hello', __name__, url_prefix='/')


@hello.route('/')
def index():
    name = request.args.get('name', 'World')
    return f'Hello {name}!'

Project/templates/bootstrap.html
<link crossorigin="anonymous" href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
      integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" rel="stylesheet">
<script crossorigin="anonymous"
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p"
        src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>

Project/templates/index.html
{% extends "layout.html" %}
{% block title %}Home{% endblock %}
{% block content %}
<div>
    {% if current_user.is_anonymous %}
    <p>Not logged in</p>
    {% else %}
    <p>Welcome {{current_user.username}}</p>
    {% endif %}
</div>
{% endblock %}

Project/templates/layout.html
<!doctype html>
<html>
<head>
    {% block head %}
    {% include "bootstrap.html" %}
    <title>{% block title %}{% endblock %} - My calc</title>
    {% endblock %}
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">MyCalc</a>
        <button aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"
                class="navbar-toggler"
                data-bs-target="#navbarSupportedContent" data-bs-toggle="collapse" type="button">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item"><a class="nav-link" href="{{ url_for('auth.home') }}">Home</a></li>
                {% if current_user.is_anonymous %}
                <li class="nav-item"><a class="nav-link" href="{{ url_for('auth.login') }}">Login</a></li>
                <li class="nav-item"><a class="nav-link" href="{{ url_for('auth.register') }}">Register</a></li>
                {% else %}
                <li class="nav-item"><a class="nav-link" href="{{ url_for('auth.profile') }}">Profile</a></li>
                {% if current_user.has_role("Admin") %}
                <li class="nav-item dropdown">
                    <a aria-expanded="false" class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#"
                       id="navbarDropdown" role="button">
                        Admin
                    </a>
                    <ul aria-labelledby="navbarDropdown" class="dropdown-menu">
                        <li><a class="dropdown-item" href="{{ url_for('admin.create_role') }}">Create Role</a></li>
                        <li><a class="dropdown-item" href="{{ url_for('admin.list_roles') }}">List Roles</a></li>
                        <li><a class="dropdown-item" href="{{ url_for('admin.assign_roles') }}">Assign Roles</a></li>
                    </ul>
                </li>
                {% endif %}
                <li class="nav-item"><a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
<div class="container-fluid">
    {% for category, message in messages %}
    <div class="alert alert-{{ category }}">{{ message }}</div>
    {% endfor %}
</div>
{% endif %}
{% endwith %}
<div class="container-fluid" id="content">{% block content %}{% endblock %}</div>
<div id="footer">
    {% block footer %}
    &copy; Copyright 2022.
    {% endblock %}
</div>
</body>
</html>

Project/templates/login.html
{% extends "layout.html" %}
{% block title %}Login{% endblock %}
{% block content %}
<h1>Login</h1>
<form action="" method="post">
    {{ form.hidden_tag() }}
    <div class="mb-3">

        {{ form.email(placeholder="email/username",
        class="form-control") }}
        {% for error in form.email.errors %}
        <p>{{ error }}</p>
        {% endfor %}
    </div>
    <div class="mb-3">
        {{ form.password(placeholder="password",
        class="form-control") }}
        {% for error in form.password.errors %}
        <p>{{ error }}</p>
        {% endfor %}
    </div>

    <div class="mb-3">{{ form.submit(class="btn btn-primary") }}
    </div>
</form>
<a class="btn btn-secondary" href="{{ url_for('auth.register') }}">Create a new Account!</a>
{% endblock %}

Project/templates/permission_denied.html
{% extends "layout.html" %}
{% block title %}Permission Denied{% endblock %}
{% block content %}
403: Permission Denied
{% endblock %}

Project/templates/profile.html
{% extends "layout.html" %}
{% block title %}Profile{% endblock %}
{% block content %}
<h1>Profile</h1>
<form action="" method="post">
    {{ form.hidden_tag() }}
    <div class="mb-3">
        {{ form.username(placeholder="username",
        class="form-control") }}
        {% for error in form.username.errors %}
        <p>{{ error }}</p>
        {% endfor %}
    </div>
    <div class="mb-3">
        {{ form.email(placeholder="email",
        class="form-control") }}
        {% for error in form.email.errors %}
        <p>{{ error }}</p>
        {% endfor %}
    </div>
    <div class="mb-3">
        {{ form.current_password(placeholder="current password",
        class="form-control") }}
        {% for error in form.current_password.errors %}
        <p>{{ error }}</p>
        {% endfor %}
    </div>
    <div class="mb-3">
        {{ form.password1(placeholder="new password",
        class="form-control") }}
        {% for error in form.password1.errors %}
        <p>{{ error }}</p>
        {% endfor %}
    </div>
    <div class="mb-3">
        {{ form.password2(placeholder="Confirm new password",
        class="form-control") }}
        {% for error in form.password2.errors %}
        <p>{{ error }}</p>
        {% endfor %}
    </div>
    <div class="mb-3">{{ form.submit(
        class="btn btn-primary") }}
    </div>
</form>
{% endblock %}

Project/templates/registration.html
{% extends "layout.html" %}
{% block title %}Registration{% endblock %}
{% block content %}
<h1>Create an Account</h1>
<form action="" method="post">
    {{ form.hidden_tag() }}
    <div class="mb-3">
        {{ form.username(placeholder="username",
        class="form-control") }}
        {% for error in form.username.errors %}
        <p>{{ error }}</p>
        {% endfor %}
    </div>
    <div class="mb-3">
        {{ form.email(placeholder="email",
        class="form-control") }}
        {% for error in form.email.errors %}
        <p>{{ error }}</p>
        {% endfor %}
    </div>
    <div class="mb-3">
        {{ form.password1(placeholder="password",
        class="form-control") }}
        {% for error in form.password1.errors %}
        <p>{{ error }}</p>
        {% endfor %}
    </div>
    <div class="mb-3">
        {{ form.password2(placeholder="Confirm password",
        class="form-control") }}
        {% for error in form.password2.errors %}
        <p>{{ error }}</p>
        {% endfor %}
    </div>
    <div class="mb-3">{{ form.submit(
        class="btn btn-primary") }}
    </div>
</form>
<a class="btn btn-secondary" href="{{ url_for('auth.login') }}">Already have an account?</a>
{% endblock %}

Project/templates/test_admin.html
{% extends "layout.html" %}
{% block title %}Test Admin{% endblock %}
{% block content %}
Welcome admin
{% endblock %}